### ISSUE TITLE
Is this supported with the Release of React-Admin v5

### ISSUE THREAD

**Issue by ccaspanello** [marmelab/ra-auth-auth0#15]
I have followed the instructions in the readme but upon successful login it seems like it just reloads the callback URL every second.

I'm wondering if this is compatible after the new release:
https://marmelab.com/blog/2024/06/20/react-admin-v5.html

**Comment by djhi** [comment]
It has not been updated for v5 yet. We'll work as soon as we can

**Comment by onlywei** [comment]
@djhi do you recommend that we begin new projects still with React-Admin v4 until `ra-auth-auth0` supports v5?

**Comment by tom-weiss** [comment]
I believe this was fixed in a release last week.

**Comment by fzaninotto** [comment]
Version 2.0.0, released last week, brings compatibility with react-admin v5. 

https://github.com/marmelab/ra-auth-auth0/releases/tag/v2.0.0
