### ISSUE TITLE
Infinite loop after login (Follow up to #4)

### ISSUE THREAD

**Issue by OtterTax** [marmelab/ra-auth-auth0#8]
This issue is a follow up to issue #4.

I am still experiencing an infinite loop even after I wrap my `<App>` component in a `<BrowserRouter>`.

The steps to reproduce are:
* Create new project with create-react-app.
* Create a simple `<Admin>` component by following the instructions [here](https://marmelab.com/react-admin/CreateReactApp.html).
* Add a data provider for auth0.
* Wrap `<App>` in `<BrowserRouter>`.

After a user authenticates, the page goes into an infinite loop.

The auth provider is very simple:
```
import { Auth0AuthProvider } from 'ra-auth-auth0';
import { Auth0Client } from '@auth0/auth0-spa-js';

const auth0 = new Auth0Client({
    domain: "OUR-DOMAIN",
    clientId: "OUR-CLIENTID",
    cacheLocation: 'localstorage'
});

export const authProvider = Auth0AuthProvider(auth0, {
    loginRedirectUri: "http://localhost:3000",
    logoutRedirectUri: "http://localhost:3000",
});
```
And here is the `<Admin>` component:
```
import { Admin, Resource, ListGuesser } from "react-admin";
import jsonServerProvider from "ra-data-json-server";
import { BrowserRouter } from "react-router-dom";
import { authProvider } from "./authProvider";

const dataProvider = jsonServerProvider("https://jsonplaceholder.typicode.com");

const GFPAdmin = () => (
  <BrowserRouter>
    <Admin dataProvider={dataProvider}
          authProvider={authProvider}>
      <Resource name="posts" list={ListGuesser} />
      <Resource name="comments" list={ListGuesser} />
    </Admin>
  </BrowserRouter>
);

export default GFPAdmin;
```

Any help resolving this issue would be appreciated.

**Comment by davidhenley** [comment]
Remove your `loginRedirectUri` from your `Auth0AuthProvider`. You are overriding the authCallback but not explicitly handling it anywhere.

```js
export const authProvider = Auth0AuthProvider(auth0, {
    logoutRedirectUri: "http://localhost:3000",
});
```

**Comment by OtterTax** [comment]
Hello David and thanks for the prompt response.

I tried removing the `loginRedirectUri` as you suggested, but I now receive an auth0 error: Callback URL mismatch.

I double checked the auth0 configuration for the application and confirmed that the allowed callback URLs, logout URLs, and web origins are all set to `http://localhost:3000`

**Comment by djhi** [comment]
Allowed callback should be set to `http://localhost:3000/auth-callback`

**Comment by OtterTax** [comment]
It's working now.  For others who may be having the same problem, here are the changes I made.

I changed the application settings in auth0:
* Allowed callback URLs: `http://localhost:3000/auth-callback`
* Allowed logout URLs: `http://localhost:3000`
* Allowed web origins: `http://localhost:3000`

I modified `authProvider.js` as follows (exactly as davidhenley suggests above):
```
import { Auth0AuthProvider } from 'ra-auth-auth0';
import { Auth0Client } from '@auth0/auth0-spa-js';

const auth0 = new Auth0Client({
    domain: "OUR-DOMAIN",
    clientId: "OUR-CLIENTID",
    cacheLocation: 'localstorage'
});

export const authProvider = Auth0AuthProvider(auth0, {
    logoutRedirectUri: "http://localhost:3000"
});
```

David and Gildas, thank you both for your help.
