### ISSUE TITLE
Infinite loop after login (Follow up to #8)

### ISSUE THREAD

**Issue by AdrianLopezGue** [marmelab/ra-auth-auth0#9]
Hi everyone! I followed the solution provided by @OtterTax in [#8](https://github.com/marmelab/ra-auth-auth0/issues/8) and the error still remains. My authclient is the following:
```ts
import { Auth0Client } from '@auth0/auth0-spa-js';
import { Auth0AuthProvider } from 'ra-auth-auth0';

export const auth0 = new Auth0Client({
  domain: "OUR_DOMAIN",
  clientId: "OUR_CLIENT_ID",
  cacheLocation: 'localstorage',
  authorizationParams: {
    audience: "OUR_AUDIENCE",
  },
});

export const auth0Provider = Auth0AuthProvider(auth0, {
  logoutRedirectUri: "http://localhost:5173",
});

```
This is my App.tsx:
```ts
import { Admin, defaultTheme } from 'react-admin';
import { BrowserRouter } from 'react-router-dom';
import { PaletteMode } from '@mui/material';

import { reactAdminDataProvider } from './infrastructure/react-admin/reactAdminDataProvider';
import { auth0Provider } from './providers/providers';

const lightTheme = defaultTheme;
const darkTheme = { ...defaultTheme, palette: { mode: 'dark' as PaletteMode } };

export const App = () => {
  return (
    <BrowserRouter>
      <Admin
        dataProvider={reactAdminDataProvider}
        authProvider={auth0Provider}
        theme={lightTheme}
        darkTheme={darkTheme}
      >
        ...
      </Admin>
    </BrowserRouter>
  );
};
```

I also tested the same code without "authorizationParams" option but the problem still remains, this is my configuration in auth0:
![image](https://github.com/marmelab/ra-auth-auth0/assets/30497404/0031ccc1-1788-4b5a-8ed7-768f53eec9fe)

Any help resolving this issue would be appreciated, thanks!!!

**Comment by AdrianLopezGue** [comment]
It seems like it is not calling handleCallback and dont know why :(

**Comment by OtterTax** [comment]
Hello AdrianLopezGue:

I'm far from an expert, but the only difference I see between your configuration and mine is the data provider.  Have you tried using a different provider to see if the problem persists?  You may want to try using JSONPlaceholder as described [here](https://marmelab.com/react-admin/Tutorial.html#using-an-api-as-data-source) to help determine whether your data provider is causing the problem.

**Comment by AdrianLopezGue** [comment]
@OtterTax I have already tested with ra-data-fakerest and custom json and the problem still remains, it should be something related to configuration

**Comment by AdrianLopezGue** [comment]
Closing because it was a problem with configuration,thanks
